---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: bento/centos-7.1

suites:
  - name: default
    run_list:
      - recipe[icewatch::database]
      - recipe[icewatch::redis]
      - recipe[icewatch::app]
      - recipe[icewatch::worker]
    attributes:
