---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[icewatch::database]
      - recipe[icewatch::redis]
      - recipe[icewatch::app]
      - recipe[icewatch::nginx]
    attributes:
