name             'icewatch'
maintainer       'Geographic Information Network of Alaska'
maintainer_email 'support@gina.alaska.edu'
license          'APACHE2'
description      'Installs/Configures icewatch'
long_description 'Installs/Configures icewatch'
version          '4.0.0'

depends 'postgresql'
depends 'database'
depends 'chef-vault'
depends 'systemd'
# depends 'nginx', '~> 2.7.0'
depends 'gina_habitat'
