inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - db/**/*.rb
    - Gemfile
    - Guardfile
    - cookbook/**/*
    - bin/**/*
    - app/controllers/concerns/gina_authentication/**/*.rb
    - app/models/concerns/gina_authentication/**/*.rb
    - test/**/*
    - config/initializers/omniauth.rb