version: '2'
services:
  postgresql:
    image: core/postgresql
    ports:
      - "5433:5432"
    environment:
      - HAB_POSTGRESQL=initdb_superuser_password='hab'
  icewatch:
    image: uafgina/icewatch
    ports:
      - "4000:4000"
    links:
      - postgresql
    environment:
      HAB_ICEWATCH: "app={port=4000}\ndb={user='hab',password='hab',port=5433}"
    command: start uafgina/icewatch --peer postgresql --bind database:postgresql.default
  proxy:
    image: uafgina/icewatch-proxy
    ports:
      - "8080:80"
    links:
      - icewatch
    command: start uafgina/icewatch-proxy --peer postgresql --bind app:icewatch.default
