#!/bin/sh
function join { local IFS="$1"; shift; echo "$*"; }

_libs=(
  "$(hab pkg path core/gcc-libs)/lib" \
  "$(hab pkg path core/imagemagick)/lib" \
  "$(hab pkg path core/libjpeg)/lib" \
  "$(hab pkg path core/libpng)/lib" \
  "$(hab pkg path core/zlib)/lib"
)

export LD_LIBRARY_PATH=$(join : ${_libs[@]})
export ICEWATCH_HOME="{{pkg.path}}"
export ICEWATCH_DATA="{{pkg.svc_data_path}}"

echo "Removing previous version deployed at ${ICEWATCH_DATA}"
rm -rf ${ICEWATCH_DATA}/*

echo "Deploying new version from ${ICEWATCH_HOME} to ${ICEWATCH_DATA}"
cp -a ${ICEWATCH_HOME}/dist ${ICEWATCH_DATA}/dist

echo "Linking database.yml"
ln -sf {{pkg.svc_config_path}}/database.yml ${ICEWATCH_DATA}/dist/config/database.yml
echo "Linking secrets.yml"
ln -sf {{pkg.svc_config_path}}/secrets.yml ${ICEWATCH_DATA}/dist/config/secrets.yml


export GEM_HOME="${ICEWATCH_DATA}/dist/vendor/bundle/ruby/2.3.0"
export GEM_PATH="$(hab pkg path core/ruby)/lib/ruby/gems/2.3.0:$(hab pkg path core/bundler):$GEM_HOME"
export PATH="$PATH:${ICEWATCH_DATA}/dist/bin:$(hab pkg path uafgina/imagemagick)/bin"
export RAILS_ENV="production"

chown -R hab:hab ${ICEWATCH_DATA}/dist
cd ${ICEWATCH_DATA}/dist

exec 2>&1

echo "Linking cache directory" 
ln -sf {{cfg.cache_path}} ${ICEWATCH_DATA}/dist/tmp/uploads

if [[ ! -f ${ICEWATCH_DATA}/.migrations_complete ]]; then
  echo "Running 'rake db:create && rake db:migrate' in ${PWD}"
  exec chpst -u hab bin/rake bootstrap && \
       touch $ICEWATCH_DATA/.migrations_complete
fi
