source 'https://supermarket.getchef.com'

# depends 'rcs-rails-application'
cookbook 'java'
cookbook 'chruby'
cookbook 'nginx'
cookbook 'postgresql'
cookbook 'database'
cookbook 'runit'
cookbook 'yum-epel'
cookbook 'yum-gina', git: 'git@github.com:gina-alaska/yum-gina-cookbook'
cookbook 'git'
cookbook 'build-essential'

metadata
