source 'https://supermarket.getchef.com'

# depends 'rcs-rails-application'
cookbook 'java'
cookbook 'rubies'
cookbook 'nginx'
cookbook 'postgresql'
cookbook 'database'
cookbook 'runit', '= 1.5.14'
cookbook 'yum-epel'
cookbook 'git'
cookbook 'build-essential'
cookbook 'chef-vault'
cookbook 'user'
cookbook 'nodejs'

metadata
