name             'icewatch'
maintainer       'Scott Macfarlane'
maintainer_email 'sdmacfarlane@alaska.edu'
license          'APACHE2'
description      'Installs/Configures icewatch'
long_description 'Installs/Configures icewatch'
version          '2.0.0'

depends 'java'
depends 'rubies'
depends 'nginx'
depends 'postgresql'
depends 'database'
depends 'runit'
depends 'yum-epel'
depends 'yum-gina'
depends 'git'
depends 'build-essential'
depends 'chef-vault'
depends 'user'
depends 'nodejs'
